### ISSUE TITLE
WE'RE HAVING TROUBLE RENDERING YOUR COMPONENT

### ISSUE THREAD

**Issue by tdoelms** [Stanford-Online/xblock-free-text-response#31]
Hello, 

I am trying to use this xblock on a newly installed Hawthorn native install, and I get the following issue:
![trouble rendering](https://user-images.githubusercontent.com/40744044/44874987-7d137600-ac62-11e8-800a-dda167bad04c.PNG)

Is there anyone that can help?

**Comment by stvstnfrd** [comment]
@tdoelms We're going to need a little more info to help out..

What version of the XBlock are you installing?

Can you post the error/output from your console so we can see the relevant logging output?

**Comment by tdoelms** [comment]
Hello, 

Thanks for your reply. I am using version 0.2.0 and the lms log shows this output:

Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 123, in get
    return self.render(request)
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 181, in render
    return render_to_response('courseware/courseware.html', self._create_courseware_context(request))
  File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/views/index.py", line 438, in _create_courseware_context
    courseware_context['fragment'] = self.section.render(STUDENT_VIEW, section_context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1903, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1310, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 810, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/seq_module.py", line 250, in student_view
    return self._student_view(context, banner_text)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/seq_module.py", line 324, in _student_view
    'items': self._render_student_view_for_items(context, display_items, fragment) if prereq_met else [],
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/seq_module.py", line 463, in _render_student_view_for_items
    rendered_item = item.render(STUDENT_VIEW, context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1903, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1310, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 810, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/vertical_block.py", line 84, in student_view
    rendered_child = child.render(STUDENT_VIEW, child_block_context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1903, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1310, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 810, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/freetextresponse/freetextresponse.py", line 309, in student_view
    'public/view.js',
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/freetextresponse/freetextresponse.py", line 255, in build_fragment
    fragment = Fragment(template.render(context))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than Context.

**Comment by stvstnfrd** [comment]
Following the sunset of the Lagunita project, this repo lives on under edx's stewardship at:
- https://github.com/edx/xblock-free-text-response

This should have support through master/Juniper already.
